name: Skylife
version: '0.1'
main: love.chihuyu.skylife.Skylife
api-version: 1.18
authors: [ Hirosuke ]
description: Original skyblock plugin for chihuyu.
website: chihuyu.love
commands:
  barter:
permissions:
  skylife.command.*:
    default: op
    children:
      skylife.command.barter: true
  skylife.command.barter:
    default: true